### ISSUE TITLE
Add convention-based registration for aggregates

### ISSUE THREAD

**Issue by jonclare** [DomainBlocks/domain-blocks#11]
At the moment, there's quite a bit of boiler plate code that's needed to set up aggregate registration.
It would be nice to have some conventions we can use to register aggregates that conform to those conventions with a minimum of code.

- [x] Assume event name is the same as the type unless specified
- [x] Aggregate persistence key and snapshot persistence key based on a property called `Id` or `$AggregateName$Id`
- [x] Events applied to a method that conforms to the expected `Apply` method for mutable or immutable state get automatically registered
- [x] ~~Commands that execute a method comforming to the expected `Execute` method for mutable or immutable state get automatically registered~~ (no longer relevant)
- [x] Initial aggregate state based on a default constructor if available

**Comment by daniel-smith** [comment]
I think the second to last checkbox isn't relevant anymore, due to the way we now execute command methods, e.g.

`var result = loadedAggregate.ExecuteCommand(x => x.DoSomething());`
