### ISSUE TITLE
Introduce explicit actions/funcs to apply events from a command execute method

### ISSUE THREAD

**Issue by jonclare** [DomainBlocks/domain-blocks#13]
We use `yield return` to yield events back to the command dispatching infrastructure.
This yields control back to the command dispatcher where we apply the event and mutate/create a new aggregate state depending on whether we're using mutable or immutable aggregates respectively.
If a consumer needs to access the new state in the immutable case, we provide a func that allows them to get the new state after yielding events.

While it works nicely, it feels a little unintuitive and we should look at an alternative using actions/funcs to allow consumers to applu events, and in the immutable case get a new aggregate state. This feels cleaner and more aligned to typical C# code.

**Comment by daniel-smith** [comment]
@jonclare - I think we can say that this one is no longer an issue after the changes in #63, right? That said, they are not "explicit" as such. Rather, they are specified during configuration time. See [ModelBuilderTests.cs](https://github.com/DomainBlocks/domain-blocks/blob/develop/src/DomainBlocks.Core.Tests/Builders/ModelBuilderTests.cs) for different scenarios.
