### ISSUE TITLE
Decouple read models/event handlers from EventPublisher subscriptions

### ISSUE THREAD

**Issue by jonclare** [DomainBlocks/domain-blocks#17]
At the moment, when you register a read model using the ASP.NET Core extension methods, you specify where to get your published events from: https://github.com/DomainBlocks/domain-blocks/blob/23b20547d4f16847048cf44d105d2d407b07c687/src/Examples/Shopping.ReadModel/Startup.cs#L35

Internally, this sets up a `HostedService` that subscribes to the underlying source and stays alive for the lifetime of the application.
That `HostedService` could potentially be reused by multiple read models using different databases/db contexts in the same service. That's not possible with how the registration is done right now, so we should allow an external subscription to be supplied when registering the read model

**Comment by daniel-smith** [comment]
Addressed with #76 and #80
