### ISSUE TITLE
Fluent API for projection config improvements

### ISSUE THREAD

**Issue by carlosrfernandez** [DomainBlocks/domain-blocks#32]
The .WithProjections() method takes an action and returns void. 

Allow for multiple fluent calls to `.WithProjections()` (potentially renaming it to `WithProjection`) as it feels a bit more natural. 

Given a consumer of the API wants to add multiple projections they would have to something like this: 

```csharp
options.WithProjections((builder, context) => {
   Projection1.Register(builder, context);
   Projection2.Register(builder, context);
}
```

Ideally it would be nice to call it as (note the method group invocation):

```csharp
options
  .WithProjection(Projection1.Register)
  .WithProjection(Projection2.Register);
}
```

**Comment by jonclare** [comment]
I think it makes sense to have both options.
You may want to register all projections from another method for example.
The singular WithProjection method is a nice addition  though

**Comment by daniel-smith** [comment]
This is no longer relevant after the changes made in #76
