### ISSUE TITLE
Allow DbContextFactory to resolve DbContexts in EF Projections

### ISSUE THREAD

**Issue by carlosrfernandez** [DomainBlocks/domain-blocks#73]
Currently in our [EntityFrameworkProjectionRegistrationBuilder](https://github.com/DomainBlocks/domain-blocks/blob/a5501145533079600622c5e1c8bc7fb818975144/src/DomainBlocks.Projections.EntityFramework.AspNetCore/EntityFrameworkProjectionRegistrationBuilder.cs#L15) we are manually creating a Scope to resolve the DbContext.

A different/more desirable pattern would be to allow the registration of a DbContextFactory and use the DbContextFactory to resolve the DbContext.

**Comment by daniel-smith** [comment]
Closed by #76
